"""base revision

Revision ID: 7f3f4bdb209e
Revises: 
Create Date: 2025-05-21 19:08:11.548373

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f3f4bdb209e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "STAGING_CHANNEL",
        sa.Column("CHANNELID", sa.Integer(), nullable=False),
        sa.Column("CHANNELCATEGORYID", sa.Integer(), nullable=False),
        sa.Column("CHANNEL", sa.String(), nullable=False),
        sa.Column("CREATEDDATE", sa.String(), nullable=True),
        sa.Column("CREATEDBY", sa.String(), nullable=True),
        sa.Column("MODIFIEDDATE", sa.String(), nullable=True),
        sa.Column("MODIFIEDBY", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("CHANNELID"),
        schema="PUBLIC",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("STAGING_CHANNEL", schema="PUBLIC")
    # ### end Alembic commands ###
