-- 2. CHANNELCATEGORY
CREATE OR REPLACE TABLE STAGING_CHANNELCATEGORY (
  CHANNELCATEGORYID    INTEGER,
  CHANNELCATEGORY      VARCHAR,
  CREATEDDATE          VARCHAR,
  CREATEDBY            VARCHAR,
  MODIFIEDDATE         VARCHAR,
  MODIFIEDBY           VARCHAR
); 