-- 8. STORE
CREATE OR REPLACE TABLE STAGING_STORE (
  STOREID              INTEGER,
  SUBSEGMENTID         INTEGER,
  STORENUMBER          INTEGER,
  STOREMANAGER         VARCHAR,
  ADDRESS              VARCHAR,
  CITY                 VARCHAR,
  STATEPROVINCE        VARCHAR,
  COUNTRY              VARCHAR,
  POSTALCODE           INTEGER,
  PHONENUMBER          VARCHAR,
  CREATEDDATE          VARCHAR,
  CREATEDBY            VARCHAR,
  MODIFIEDDATE         VARCHAR,
  MODIFIEDBY           VARCHAR
); 