-- 10. SALESHEADER
CREATE OR REPLACE TABLE STAGING_SALESHEADER (
  SALESHEADERID        INTEGER,
  DATE                 VARCHAR,
  CHANNELID            INTEGER,
  STOREID              INTEGER,
  CUSTOMERID           VARCHAR,
  RESELLERID           VARCHAR,
  CREATEDDATE          VARCHAR,
  CREATEDBY            VARCHAR,
  MODIFIEDDATE         VARCHAR,
  MODIFIEDBY           VARCHAR
); 