-- 9. SALESDETAIL
CREATE OR REPLACE TABLE STAGING_SALESDETAIL (
  SALESDETAILID        INTEGER,
  SALESHEADERID        INTEGER,
  PRODUCTID            INTEGER,
  SALESQUANTITY        INTEGER,
  SALESAMOUNT          VARCHAR,
  CREATEDDATE          VARCHAR,
  CREATEDBY            VARCHAR,
  MODIFIEDDATE         VARCHAR,
  MODIFIEDBY           VARCHAR
); 