-- 7. RESELLER
CREATE OR REPLACE TABLE STAGING_RESELLER (
  RESELLERID           VARCHAR,
  CONTACT              VARCHAR,
  EMAILADDRESS         VARCHAR,
  ADDRESS              VARCHAR,
  CITY                 VARCHAR,
  STATEPROVINCE        VARCHAR,
  COUNTRY              VARCHAR,
  POSTALCODE           INTEGER,
  PHONENUMBER          VARCHAR,
  CREATEDDATE          VARCHAR,
  CREATEDBY            VARCHAR,
  MODIFIEDDATE         VARCHAR,
  MODIFIEDBY           VARCHAR,
  RESELLERNAME         VARCHAR
); 