-- 11. TARGETDATACHANNEL
CREATE OR REPLACE TABLE STAGING_TARGETDATACHANNEL (
  YEAR                 INTEGER,
  CHANNELNAME          VARCHAR,
  TARGETNAME           VARCHAR,
  TARGETSALESAMOUNT    INTEGER
); 