-- 12. TARGETDATAPRODUCT
CREATE OR REPLACE TABLE STAGING_TARGETDATAPRODUCT (
  PRODUCTID            INTEGER,
  PRODUCT              VARCHAR,
  YEAR                 INTEGER,
  SALESQUANTITYTARGET  INTEGER
); 