-- 1. CHANNEL
CREATE OR REPLACE TABLE STAGING_CHANNEL (
  CHANNELID            INTEGER,
  CHANNELCATEGORYID    INTEGER,
  CHANNEL              VARCHAR,
  CREATEDDATE          VARCHAR,
  CREATEDBY            VARCHAR,
  MODIFIEDDATE         VARCHAR,
  MODIFIEDBY           VARCHAR
); 