-- 6. PRODUCTTYPE
CREATE OR REPLACE TABLE STAGING_PRODUCTTYPE (
  PRODUCTTYPEID        INTEGER,
  PRODUCTCATEGORYID    INTEGER,
  PRODUCTTYPE          VARCHAR,
  CREATEDDATE          VARCHAR,
  CREATEDBY            VARCHAR,
  MODIFIEDDATE         VARCHAR,
  MODIFIEDBY           VARCHAR
); 