-- 5. PRODUCTCATEGORY
CREATE OR REPLACE TABLE STAGING_PRODUCTCATEGORY (
  PRODUCTCATEGORYID    INTEGER,
  PRODUCTCATEGORY      VARCHAR,
  CREATEDDATE          VARCHAR,
  CREATEDBY            VARCHAR,
  MODIFIEDDATE         VARCHAR,
  MODIFIEDBY           VARCHAR
); 