-- 3. CUSTOMER
CREATE OR REPLACE TABLE STAGING_CUSTOMER (
  CUSTOMERID           VARCHAR,
  SUBSEGMENTID         INTEGER,
  FIRSTNAME            VARCHAR,
  LASTNAME             VARCHAR,
  GENDER               VARCHAR,
  EMAILADDRESS         VARCHAR,
  ADDRESS              VARCHAR,
  CITY                 VARCHAR,
  STATEPROVINCE        VARCHAR,
  COUNTRY              VARCHAR,
  POSTALCODE           INTEGER,
  PHONENUMBER          VARCHAR,
  CREATEDDATE          VARCHAR,
  CREATEDBY            VARCHAR,
  MODIFIEDDATE         VARCHAR,
  MODIFIEDBY           VARCHAR
); 